import styles from "./RepoContainerPage.module.scss";
import RepoCard from "../RepoCard";

function RepoContainerPage() {
  const repos = [
    {
      html_url: "https://github.com/atmos/aloha_2009",
      description:
        "my talk on open source business models and independent record labels",
      created_at: "2009-09-09T07:36:19Z",
      updated_at: "2018-03-25T12:49:53Z",
      visibility: "public",
      language: null,
      default_branch: "master",
      size: 80804,
      id: 38,
      name: "aloha_2009",
    },
    {
      html_url: "https://github.com/atmos/appsly-android-rest",
      description: "An Android client library for RESTful based web services.",
      created_at: "2014-02-04T19:29:17Z",
      updated_at: "2020-03-16T12:33:29Z",
      visibility: "public",
      language: "Java",
      default_branch: "master",
      size: 652,
      id: 38,
      name: "appsly-android-rest",
    },
    {
      html_url: "https://github.com/atmos/as_time_goes_by",
      description:
        "an example sinatra/rspec/datamapper/webrat app with selenium built in",
      created_at: "2009-02-12T01:24:18Z",
      updated_at: "2019-08-13T14:00:17Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 80,
      id: 38,
      name: "as_time_goes_by",
    },
    {
      html_url: "https://github.com/atmos/atmos-dot-org-netlify",
      description: null,
      created_at: "2018-03-18T17:18:06Z",
      updated_at: "2024-03-12T12:43:03Z",
      visibility: "public",
      language: "CSS",
      default_branch: "master",
      size: 11480,
      id: 38,
      name: "atmos-dot-org-netlify",
    },
    {
      html_url: "https://github.com/atmos/atmos-rails",
      description: "A simple rails 4 template for resque and github oauth",
      created_at: "2013-10-10T03:09:51Z",
      updated_at: "2019-08-13T15:28:01Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 197,
      id: 38,
      name: "atmos-rails",
    },
    {
      html_url: "https://github.com/atmos/atmos.github.io",
      description: null,
      created_at: "2008-12-17T07:22:39Z",
      updated_at: "2023-03-10T11:50:25Z",
      visibility: "public",
      language: "HTML",
      default_branch: "master",
      size: 755,
      id: 38,
      name: "atmos.github.io",
    },
    {
      html_url: "https://github.com/atmos/atmos.org",
      description: "redirect shit from heroku to github pages",
      created_at: "2011-08-25T11:27:23Z",
      updated_at: "2023-03-10T11:51:00Z",
      visibility: "public",
      language: "JavaScript",
      default_branch: "master",
      size: 96,
      id: 38,
      name: "atmos.org",
    },
    {
      html_url: "https://github.com/atmos/atmos.org-redirector",
      description: "redirect atmos.org on ec2 to www.atmos.org on github",
      created_at: "2010-01-09T20:11:09Z",
      updated_at: "2023-03-10T11:50:32Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 682,
      id: 38,
      name: "atmos.org-redirector",
    },
    {
      html_url: "https://github.com/atmos/braintree_transparent_redirect_slice",
      description:
        "A slice for interfacing with braintree's transparent redirect stuff in a merb app",
      created_at: "2009-01-03T00:42:12Z",
      updated_at: "2019-08-13T13:51:09Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 148,
      id: 38,
      name: "braintree_transparent_redirect_slice",
    },
    {
      html_url: "https://github.com/atmos/brute-force-your-router",
      description: null,
      created_at: "2014-12-26T23:38:02Z",
      updated_at: "2016-02-11T17:14:40Z",
      visibility: "public",
      language: "Lua",
      default_branch: "master",
      size: 116,
      id: 38,
      name: "brute-force-your-router",
    },
    {
      html_url: "https://github.com/atmos/bugzilla",
      description:
        "Read-only mirror of Bugzilla source from git.mozilla.org/bugzilla/bugzilla.git",
      created_at: "2014-05-28T17:24:54Z",
      updated_at: "2018-02-18T20:45:15Z",
      visibility: "public",
      language: "Perl",
      default_branch: "master",
      size: 17538,
      id: 38,
      name: "bugzilla",
    },
    {
      html_url: "https://github.com/atmos/bundler",
      description: "Manage your application's gem dependencies with less pain",
      created_at: "2010-10-06T02:17:37Z",
      updated_at: "2020-01-10T01:11:24Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 6995,
      id: 38,
      name: "bundler",
    },
    {
      html_url: "https://github.com/atmos/bundler-site",
      description: null,
      created_at: "2010-09-09T08:10:24Z",
      updated_at: "2020-01-10T01:09:34Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 294,
      id: 38,
      name: "bundler-site",
    },
    {
      html_url: "https://github.com/atmos/butt",
      description: "Unofficial fork of http://danielnoethen.de/",
      created_at: "2012-12-26T03:29:22Z",
      updated_at: "2019-08-27T18:32:21Z",
      visibility: "public",
      language: "C++",
      default_branch: "master",
      size: 246,
      id: 38,
      name: "butt",
    },
    {
      html_url: "https://github.com/atmos/camo",
      description: ":lock: an http proxy to route images through SSL",
      created_at: "2010-11-13T02:56:46Z",
      updated_at: "2024-04-17T21:22:01Z",
      visibility: "public",
      language: "CoffeeScript",
      default_branch: "master",
      size: 215,
      id: 38,
      name: "camo",
    },
    {
      html_url: "https://github.com/atmos/campfiyah",
      description: "Faraday API for Campfire",
      created_at: "2013-04-09T21:33:52Z",
      updated_at: "2018-02-18T20:45:35Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 316,
      id: 38,
      name: "campfiyah",
    },
    {
      html_url: "https://github.com/atmos/capybara-standalone",
      description: "rspec2 and capybara testing, a simple example.",
      created_at: "2010-12-14T07:11:35Z",
      updated_at: "2023-11-07T16:42:36Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 90,
      id: 38,
      name: "capybara-standalone",
    },
    {
      html_url: "https://github.com/atmos/charlock_holmes",
      description: "Character encoding detection, brought to you by ICU",
      created_at: "2012-10-08T23:53:47Z",
      updated_at: "2013-12-27T17:06:02Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 35513,
      id: 38,
      name: "charlock_holmes",
    },
    {
      html_url: "https://github.com/atmos/chef",
      description:
        "A systems integration framework, built to bring the benefits of configuration management to your entire infrastructure.",
      created_at: "2010-08-08T23:59:46Z",
      updated_at: "2018-02-18T20:45:56Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 38277,
      id: 38,
      name: "chef",
    },
    {
      html_url: "https://github.com/atmos/ciderapp.org",
      description: "the site that serves up your recipes",
      created_at: "2010-05-22T21:46:48Z",
      updated_at: "2024-02-05T21:15:10Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 694,
      id: 38,
      name: "ciderapp.org",
    },
    {
      html_url: "https://github.com/atmos/cinderella",
      description: "how your apple laptop should work",
      created_at: "2010-08-31T23:10:02Z",
      updated_at: "2023-01-28T21:30:00Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 1147,
      id: 38,
      name: "cinderella",
    },
    {
      html_url: "https://github.com/atmos/connect",
      description: "Connect is a middleware layer for Node.js",
      created_at: "2010-08-22T19:37:34Z",
      updated_at: "2018-02-18T20:46:07Z",
      visibility: "public",
      language: "JavaScript",
      default_branch: "master",
      size: 3007,
      id: 38,
      name: "connect",
    },
    {
      html_url: "https://github.com/atmos/connect-auth",
      description: "Authentication middleware for connect.",
      created_at: "2010-08-23T21:26:05Z",
      updated_at: "2018-02-18T20:46:11Z",
      visibility: "public",
      language: "JavaScript",
      default_branch: "master",
      size: 247,
      id: 38,
      name: "connect-auth",
    },
    {
      html_url: "https://github.com/atmos/conveyor",
      description: "A fast build system for Docker images.",
      created_at: "2016-02-07T03:50:50Z",
      updated_at: "2018-02-18T20:46:15Z",
      visibility: "public",
      language: "Go",
      default_branch: "master",
      size: 1331,
      id: 38,
      name: "conveyor",
    },
    {
      html_url: "https://github.com/atmos/developer.github.com",
      description: "GitHub API documentation",
      created_at: "2013-03-15T03:55:46Z",
      updated_at: "2017-01-09T10:29:54Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 4206,
      id: 38,
      name: "developer.github.com",
    },
    {
      html_url: "https://github.com/atmos/django-headcrumbs",
      description: "Smart and easy-to-use breadcrumbs for Django",
      created_at: "2013-03-08T17:23:44Z",
      updated_at: "2018-02-18T20:46:23Z",
      visibility: "public",
      language: "Python",
      default_branch: "master",
      size: 83,
      id: 38,
      name: "django-headcrumbs",
    },
    {
      html_url: "https://github.com/atmos/djcharts-menubar",
      description: "djcharts.io menubar item",
      created_at: "2014-12-10T03:59:02Z",
      updated_at: "2018-02-18T20:46:28Z",
      visibility: "public",
      language: "Objective-C",
      default_branch: "master",
      size: 9244,
      id: 38,
      name: "djcharts-menubar",
    },
    {
      html_url: "https://github.com/atmos/docker-unifi-controller",
      description: null,
      created_at: "2016-02-17T01:18:08Z",
      updated_at: "2018-03-01T05:25:33Z",
      visibility: "public",
      language: null,
      default_branch: "master",
      size: 3,
      id: 38,
      name: "docker-unifi-controller",
    },
    {
      html_url: "https://github.com/atmos/dot_xen",
      description: "parsing xen's .xen files for reading and writing",
      created_at: "2008-06-28T19:31:04Z",
      updated_at: "2019-08-13T13:27:52Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 108,
      id: 38,
      name: "dot_xen",
    },
    {
      html_url: "https://github.com/atmos/elasticsearch-client",
      description: null,
      created_at: "2012-06-12T23:25:17Z",
      updated_at: "2018-02-18T20:46:41Z",
      visibility: "public",
      language: "Ruby",
      default_branch: "master",
      size: 99,
      id: 38,
      name: "elasticsearch-client",
    },
  ];
  return (
    <div className={styles.main}>
      {repos.map((item) => (
        <RepoCard repo={item} />
      ))}
    </div>
  );
}

export default RepoContainerPage;
